format = """
[](color_bg1)\
$os\
[](bg:color_bg3 fg:color_bg1)\
$directory\
[](fg:color_bg3 bg:color_yellow)\
$git_branch\
$git_status\
[](fg:color_yellow bg:color_blue)\
$time\
[ ](fg:color_blue)\
$cmd_duration\
$line_break\
$character
"""

palette = 'dark_theme'

[os]
disabled = false
style = "bg:color_bg1"

[os.symbols]
Windows = "󰍲 "
Ubuntu = "󰕈 "
SUSE = " "
Raspbian = "󰐿 "
Mint = "󰣭 "
Macos = "󰀵 "
Manjaro = " "
Linux = "󰌽 "
Gentoo = "󰣨 "
Fedora = "󰣛 "
Alpine = " "
Amazon = " "
Android = " "
AOSC = " "
Arch = "󰣇 "
Artix = "󰣇 "
EndeavourOS = " "
CentOS = " "
Debian = "󰣚 "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "
Pop = " "

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:color_bg1"
style_root = "bg:color_bg1"
format = '[$user ]($style)'

[directory]
style = "bg:color_bg3"
format = "[ $path ]($style)"
truncation_length = 0
truncate_to_repo = false

#[directory.substitutions]
#"Documents" = "󰈙 "
#"Downloads" = " "
#"Music" = "󰝚 "
#"Pictures" = " "
#"Developer" = "󰲋 "
#"code" = "󰲋 "


[git_branch]
symbol = ""
style = "bg:color_yellow"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:color_yellow"
format = '[$all_status$ahead_behind ]($style)'
ahead = "⇡${count}"
diverged = "⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
modified = "!${count}"
untracked = "?${count}"
staged = "+${count}"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:color_blue"
format = '[ $time ]($style)'

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'

[cmd_duration]
show_milliseconds = false
format = "  $duration "
style = "bg:lavender"
disabled = false
show_notifications = false
min_time_to_notify = 45000

[palettes.dark_theme]
color_fg0 = '#fbf1c7'
color_bg1 = '#3B4252'
color_bg3 = '#434C5E'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'